#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

HISTFILE=~/.history
SAVEHIST=50000
HISTSIZE=50000

export FZF_DEFAULT_COMMAND='fd --type f'

export PATH=\
$HOME/Applications/bin:\
/usr/local/bin:\
$HOME/.yarn/bin:\
$HOME/.config/yarn/global/node_modules/.bin:\
$PATH

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/jjc/Desktop/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/jjc/Desktop/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/jjc/Desktop/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/jjc/Desktop/google-cloud-sdk/completion.zsh.inc'; fi

EDITOR=nvim

export NVIM_TUI_ENABLE_TRUE_COLOR=1

LOCAL_ZPROFILE="${ZDOTDIR:-$HOME}/.zsh/zprofile.local"
if [ -f "${LOCAL_ZPROFILE}" ]; then
    source "${LOCAL_ZPROFILE}"
fi
