#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias ls='ls -G -F'
alias fn='find . -name'
alias grep='grep --color'

fgrep () { find . -name "$1" -exec grep --color -H "$2" "{}" \; }
fgrepj () { find . -name "*.java" -exec grep --color -H "$1" "{}" \; }
fgrepp () { find . -name "*.py" -exec grep --color -H "$1" "{}" \; }
fnvim () { find . -name "$1" -exec vim "{}" \; }

function title() {
  if [[ "$TERM" == ((x|a|ml|dt|E)term*|(u|)rxvt*) ]]; then
    printf "\e]1;%s\a" ${(V)argv}
  fi
}

KEYTIMEOUT=1

setopt autocd
setopt nohup
setopt no_check_jobs
setopt ignoreEOF
setopt inc_append_history
setopt hist_ignore_dups
setopt nomenucomplete
setopt noautomenu
setopt nocorrect

bindkey -v

bindkey                 "^R" history-incremental-search-backward
bindkey                 "^N" history-incremental-search-forward

autoload -U compinit
compinit

autoload zmv

LOCAL_ZSHRC="${ZDOTDIR:-$HOME}/.zsh/zshrc.local"
if [ -f "${LOCAL_ZSHRC}" ]; then
    source "${LOCAL_ZSHRC}"
fi

# Simplify prompt so as to not confuse Emacs TRAMP.
[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ '
